title: Let’s RP Technical Support
description: Let’s RP Technical Support Repository
theme: just-the-docs

url: https://letsrp.co.uk

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/LRP_Reboot_Logo-1.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/LRP_Reboot_Logo-1TS.png"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
